package httpapi

func (r *Router) routes() {
	r.handle("GET /", r.yggMetadata)
	r.handle("POST /site-login", r.siteLogin)
	r.handle("POST /site-logout", r.siteLogout)
	r.handle("POST /register", r.register)
	r.handle("POST /send-verification-code", r.sendVerificationCode)
	r.handle("POST /reset-password", r.resetPassword)
	r.handle("GET /me", r.auth(r.me, false))
	r.handle("PATCH /me", r.auth(r.updateMe, false))
	r.handle("DELETE /me", r.auth(r.deleteMe, false))
	r.handle("POST /me/password", r.auth(r.changePassword, false))
	r.handle("POST /me/refresh-token", r.refreshToken)
	r.handle("GET /me/profiles", r.auth(r.listMyProfiles, false))
	r.handle("POST /me/profiles", r.auth(r.createProfile, false))
	r.handle("PATCH /me/profiles/{pid}", r.auth(r.updateProfile, false))
	r.handle("DELETE /me/profiles/{pid}", r.auth(r.deleteProfile, false))
	r.handle("DELETE /me/profiles/{pid}/skin", r.auth(r.clearProfileSkin, false))
	r.handle("DELETE /me/profiles/{pid}/cape", r.auth(r.clearProfileCape, false))
	r.handle("GET /me/textures", r.auth(r.listMyTextures, false))
	r.handle("POST /me/textures", r.auth(r.uploadMyTexture, false))
	r.handle("GET /me/textures/{hash}/{texture_type}", r.auth(r.textureDetail, false))
	r.handle("PATCH /me/textures/{hash}/{texture_type}", r.auth(r.updateTexture, false))
	r.handle("DELETE /me/textures/{hash}/{texture_type}", r.auth(r.deleteTexture, false))
	r.handle("POST /me/textures/{hash}/add", r.auth(r.addTexture, false))
	r.handle("POST /me/textures/{hash}/apply", r.auth(r.applyTexture, false))
	r.handle("POST /textures/upload", r.auth(r.uploadAndApplyTexture, false))
	r.handle("GET /public/skin-library", r.publicLibrary)
	r.handle("GET /public/settings", r.publicSettings)
	r.handle("GET /public/carousel", r.publicCarousel)

	r.handle("POST /authserver/authenticate", r.yggAuthenticate)
	r.handle("POST /authserver/refresh", r.yggRefresh)
	r.handle("POST /authserver/validate", r.yggValidate)
	r.handle("POST /authserver/invalidate", r.yggInvalidate)
	r.handle("POST /authserver/signout", r.yggSignout)
	r.handle("POST /sessionserver/session/minecraft/join", r.yggJoin)
	r.handle("GET /sessionserver/session/minecraft/hasJoined", r.yggHasJoined)
	r.handle("GET /sessionserver/session/minecraft/profile/{uuid}", r.yggProfile)
	r.handle("GET /api/users/profiles/minecraft/{playerName}", r.lookupName)
	r.handle("GET /users/profiles/minecraft/{playerName}", r.lookupName)
	r.handle("GET /api/profiles/minecraft/{playerName}", r.lookupName)
	r.handle("POST /api/profiles/minecraft", r.lookupNames)
	r.handle("GET /api/minecraft/profile/lookup/name/{playerName}", r.lookupName)
	r.handle("GET /minecraft/profile/lookup/name/{playerName}", r.lookupName)
	r.handle("PUT /api/user/profile/{uuid}/{texture_type}", r.yggUploadTexture)
	r.handle("DELETE /api/user/profile/{uuid}/{texture_type}", r.yggDeleteTexture)
	r.handle("GET /microsoft/auth-url", r.auth(r.microsoftAuthURL, false))
	r.handle("GET /microsoft/callback", r.microsoftCallback)
	r.handle("POST /microsoft/get-profile", r.auth(r.microsoftGetProfile, false))
	r.handle("POST /microsoft/import-profile", r.auth(r.microsoftImportProfile, false))
	r.handle("POST /remote-ygg/get-profiles", r.auth(r.remoteYggGetProfiles, false))
	r.handle("POST /remote-ygg/import-profile", r.auth(r.remoteYggImportProfile, false))
	r.handle("POST /remote-ygg/import-profiles", r.auth(r.remoteYggImportProfiles, false))

	r.handle("GET /admin/users", r.auth(r.adminUsers, true))
	r.handle("GET /admin/users/{user_id}/profiles", r.auth(r.adminUserProfiles, true))
	r.handle("POST /admin/users/{user_id}/toggle-admin", r.auth(r.adminToggleUserAdmin, true))
	r.handle("DELETE /admin/users/{user_id}", r.auth(r.adminDeleteUser, true))
	r.handle("POST /admin/users/{user_id}/ban", r.auth(r.adminBanUser, true))
	r.handle("POST /admin/users/{user_id}/unban", r.auth(r.adminUnbanUser, true))
	r.handle("POST /admin/users/reset-password", r.auth(r.adminResetUserPassword, true))
	r.handle("GET /admin/profiles", r.auth(r.adminProfiles, true))
	r.handle("PATCH /admin/profiles/{profile_id}", r.auth(r.adminUpdateProfile, true))
	r.handle("DELETE /admin/profiles/{profile_id}", r.auth(r.adminDeleteProfile, true))
	r.handle("PATCH /admin/profiles/{profile_id}/skin", r.auth(r.adminUpdateProfileSkin, true))
	r.handle("PATCH /admin/profiles/{profile_id}/cape", r.auth(r.adminUpdateProfileCape, true))
	r.handle("GET /admin/textures", r.auth(r.adminTextures, true))
	r.handle("PATCH /admin/textures/{hash}", r.auth(r.adminUpdateTexture, true))
	r.handle("DELETE /admin/textures/{hash}", r.auth(r.adminDeleteTexture, true))
	r.handle("GET /admin/invites", r.auth(r.adminInvites, true))
	r.handle("POST /admin/invites", r.auth(r.adminCreateInvite, true))
	r.handle("DELETE /admin/invites/{code}", r.auth(r.adminDeleteInvite, true))
	r.handle("GET /admin/official-whitelist", r.auth(r.adminOfficialWhitelist, true))
	r.handle("POST /admin/official-whitelist", r.auth(r.adminAddOfficialWhitelist, true))
	r.handle("DELETE /admin/official-whitelist/{username}", r.auth(r.adminRemoveOfficialWhitelist, true))
	r.handle("POST /admin/carousel", r.auth(r.adminUploadCarousel, true))
	r.handle("DELETE /admin/carousel/{filename}", r.auth(r.adminDeleteCarousel, true))
	r.handle("GET /admin/settings/site", r.auth(r.adminGetSiteSettings, true))
	r.handle("POST /admin/settings/site", r.auth(r.adminSaveSiteSettings, true))
	r.handle("GET /admin/settings/{group}", r.auth(r.adminGetSettingsGroup, true))
	r.handle("POST /admin/settings/{group}", r.auth(r.adminSaveSettingsGroup, true))
}
